# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 693dd0d10dcb912bd7cdde4e24679f529d3725465ad19253bfb3f57ca8ac58b728a7fbac5880d2d0b66fd8c6e7e972c3e0f6de8201b4ef9f347ff291ac82e87c

test:
  secret_key_base: c77cf57fa6568dd0d179edc5fbfeecf82bb79c9a802776eeacd3cfb7329cd3e3b11fe92d90648df4475dc34bdf690c3634d225d74b61347a36db6f666e9372a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
